version: '3'
services:
  frontend:
    image: my_app_frontend:1.5
    build:
      context: ./frontend/
    ports:
      - "3000:3000"
  shared:
    image: mongo:latest
    build: .
    environment:
      DATABASE_URL: "mongodb+srv://amarnadagera01:lnvtV0kN1JUGbP7D@cluster0.mbvrpfb.mongodb.net/starter crm app%20database?retryWrites=true&w=majority"
    ports:
       - "3001:8888"

