version: '3'
services:
  frontend:
    build:
      context: node-js-deployment-/frontend/
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"

  shared:
    build: .
    ports:
      - "3001:3001"

    
