version: '3'
 services:
  frontend:
    image: frontend:1.4
    build:
      context: ./frontend/
    ports:
      - "3000:3000"
    
  shared:
    image: my_app:1.4
    build: .
  mongo:
    image: mongo:latest
    environment:
      DATABASE_URL: mongodb+srv://amarnadagera01:lnvtV0kN1JUGbP7D@cluster0.mbvrpfb.mongodb.net/starter crm app database?retryWrites=true&w=majorit
    ports:
      - "3001:8000"
  
    
